# Generated by Django 2.0.5 on 2018-06-17 20:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180617_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='unique id for the particular book', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Available'), ('O', 'On Loan'), ('R', 'Reserved'), ('M', 'Maintatnce')], default='A', help_text='Enter the books status', max_length=1)),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['surname', 'first_name']},
        ),
    ]
