# Generated by Django 2.0.5 on 2018-06-17 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180617_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialet_used', models.CharField(choices=[('E', 'English'), ('F', 'French'), ('C', 'Chinese'), ('I', 'Italia')], default='E', max_length=1)),
                ('local_dialet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.BookInstance')),
            ],
        ),
    ]
