# Generated by Django 2.0.5 on 2018-06-25 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0007_bookinstance_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='dialet_used',
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='language',
            name='local_dialet',
            field=models.CharField(help_text='enter the books Language', max_length=200),
        ),
    ]
