# Generated by Django 2.0.5 on 2018-07-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20180625_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='D_O_D',
            field=models.DateField(blank=True, null=True, verbose_name='died'),
        ),
    ]
