# Generated by Django 2.0.5 on 2018-09-06 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_profile'),
        ('catalog', '0011_auto_20180718_1335'),
    ]

    operations = [
    ]
